favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.3595745
  brandStrength: 1
  rhythmicContrast: 0.680851
  brandColors:
    - '#E9ECE9'
    - '#272828'
    - '#B49A77'
    - '#FCB402'
    - '#65A3C6'
  lightness: 0.2085106
typography_spectrum: 0.3382979
layout_spectrum: 0.5859697808045894
analytics:
  twitter: null
  google: null
  facebook: null
name: Lost and Found
