name: Lost and Found
favicon: null
layout_spectrum: 0.5859697808045894
typography_spectrum: 0.5159065544139594
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.19783336552791297
  lightness: 0.0950961911585182
  saturation: 0.6854182863608003
  rhythmicContrast: 0.5151446824893355
purpose: []
